### ISSUE TITLE
Inisiasi Styleguide

### ISSUE THREAD

**Issue by logos-engineer** [logos-engineer/microsite-logos#3]
implementasikan styleguide design ke dalam theme Chakra UI. Contoh bisa dilihat pada 
- [Theme Chakra Example](https://github.com/naufaldi/nextjs-chakra-notion-blog/blob/main/src/theme.js)
- [Theme Chakra Example 2](https://github.com/mazipan/ksana.in/blob/master/src/theme.ts)

Implementasi berupa 
- Color
- Breakpoints
- Typography

**Comment by Aqshola** [comment]
Dalam Pengerjaan - Aqshola

**Comment by logos-engineer** [comment]
okee
