### ISSUE TITLE
Implementasi Design Hero Dekstop

### ISSUE THREAD

**Issue by logos-engineer** [logos-engineer/microsite-logos#4]
Melakukan implementasi design ke kode versi dekstop bagian hero section.
Contoh kode di 
- [Ksana.in](https://github.com/mazipan/ksana.in/tree/master/src/pages)
- [NextJS Blog](https://github.com/naufaldi/nextjs-chakra-notion-blog/tree/main/src/pages)
- [Future Bright](https://github.com/naufaldi/future-bright)

**Comment by naufaldi** [comment]
aku mengambil pekerjaan ini

**Comment by Aqshola** [comment]
Dalam pengerjaan untuk fix hero disesuaikan dengan style yang baru
