### ISSUE TITLE
Component Layout

### ISSUE THREAD

**Issue by logos-engineer** [logos-engineer/microsite-logos#5]
Membuat Component layout untuk header dan footer. 
Contoh kode di 
- [Ksana.in](https://github.com/mazipan/ksana.in/tree/master/src/pages)
- [NextJS Blog](https://github.com/naufaldi/nextjs-chakra-notion-blog/tree/main/src/pages)
- [Future Bright](https://github.com/naufaldi/future-bright)

**Comment by naufaldi** [comment]
implementasikan layouting untuk compoennt
